baseURL = 'http://pronto-solutions.github.io/product-page'
languageCode = 'en-us'
title = 'Pronto Solutions'
theme = "spectral"
publishDir = "docs"


[params]
fancyTitle = "Pronto" # title for frontpage, may include image
copyright = "Pronto Solutions"
description = 'AI Powered solutions for more intuitive dining experience'
startbuttonText = "Activate"
startbuttonLink = "#one"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Want to know when your customers need service? Pronto does that for you.'
body = '''
With our cutting edge technology, Pronto tells you exactly when your restaraunt patrons need one-on-one attention. 

No buttons, no gimicks, straight service.
'''

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-bell"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/food-plate.jpg"
title = 'Real time Understanding'
body = 'PRONTO provides restaraunts with real time understanding of diner status. From sit-down to clean-up, Pronto lets you know exactly when your patrons need you the most.'

[[params.two.section]]
img = "img/customer-happy.jpg"
title = 'Personalized Customer Experience'
body = 'Let your customers immerse themselves in your atmosphere and tailor the experience they will never forget. PRONTO provides restaurants with the tools to personalized customer experience without a hinderence.'

[[params.two.section]]
img = "img/group.jpg"
title = 'Deeper Awareness'
body = 'With a timeline of events, PRONTO captures a better understanding of customer experience and interaction.'

[params.three]
enable = true
title = 'How does it work?'
body = '''
Pronto understands social cues at an individual table level and helps you make informed decisions by serving you with data exactly how you need it.
'''

[[params.three.feature]]
icon = "fa-tachometer"
title = "Lightning Speed"
body = "Pronto's cutting edge AI returns instanaeous results to keep you up to date on where your attention is needed the most."

[[params.three.feature]]
icon = "fa-lock"
title = "Security First"
body = "Privacy comes first. That means all data is processed locally at the table, only what is necessary is shared."

[[params.three.feature]]
icon = "fa-television"
title = "Intuitive UI"
body = "Service is fast, and Pronto is faster. One quick glance at our user interface and you'll know exactly who needs help."

[[params.three.feature]]
icon = "fa-expand"
title = "Flexible for You"
body = "No restaraunt is the same. Pronto brings insight to the key experiences that your customers embed themselves in and you drive how to serve them the moments of a lifetime"

[[params.three.feature]]
icon = "fa-stop"
title = "Discrete Footprint"
body = "Small and Mighty. Pronto attaches to your dining surfaces quickly, discretely, and without any upkeep necessary. Pronto works for you."

[[params.three.feature]]
icon = "fa-area-chart"
title = "True Analytics"
body = "Capture insights at the source. Pronto tells you exactly customers are spending the most time giving you a better understanding of where you can serve them best."

[params.cta]
enable = true
title = "Lets get Started"
body = "Want to learn how pronto works? Check out our technical archive about the behind the scenes."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
